// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protoService/remiderService.proto

package protoService

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PRIORITY int32

const (
	PRIORITY_LOW  PRIORITY = 0
	PRIORITY_MID  PRIORITY = 1
	PRIORITY_HIGH PRIORITY = 2
)

var PRIORITY_name = map[int32]string{
	0: "LOW",
	1: "MID",
	2: "HIGH",
}

var PRIORITY_value = map[string]int32{
	"LOW":  0,
	"MID":  1,
	"HIGH": 2,
}

func (x PRIORITY) String() string {
	return proto.EnumName(PRIORITY_name, int32(x))
}

func (PRIORITY) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2d3f97059af3282a, []int{0}
}

type Task struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	LimitDate            string   `protobuf:"bytes,3,opt,name=limit_date,json=limitDate,proto3" json:"limit_date,omitempty"`
	Tags                 []string `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`
	TeamName             string   `protobuf:"bytes,5,opt,name=team_name,json=teamName,proto3" json:"team_name,omitempty"`
	Priority             PRIORITY `protobuf:"varint,6,opt,name=priority,proto3,enum=remiderService.PRIORITY" json:"priority,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Task) Reset()         { *m = Task{} }
func (m *Task) String() string { return proto.CompactTextString(m) }
func (*Task) ProtoMessage()    {}
func (*Task) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d3f97059af3282a, []int{0}
}

func (m *Task) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Task.Unmarshal(m, b)
}
func (m *Task) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Task.Marshal(b, m, deterministic)
}
func (m *Task) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Task.Merge(m, src)
}
func (m *Task) XXX_Size() int {
	return xxx_messageInfo_Task.Size(m)
}
func (m *Task) XXX_DiscardUnknown() {
	xxx_messageInfo_Task.DiscardUnknown(m)
}

var xxx_messageInfo_Task proto.InternalMessageInfo

func (m *Task) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Task) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Task) GetLimitDate() string {
	if m != nil {
		return m.LimitDate
	}
	return ""
}

func (m *Task) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *Task) GetTeamName() string {
	if m != nil {
		return m.TeamName
	}
	return ""
}

func (m *Task) GetPriority() PRIORITY {
	if m != nil {
		return m.Priority
	}
	return PRIORITY_LOW
}

type TaskRequest struct {
	Task                 *Task    `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TaskRequest) Reset()         { *m = TaskRequest{} }
func (m *TaskRequest) String() string { return proto.CompactTextString(m) }
func (*TaskRequest) ProtoMessage()    {}
func (*TaskRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d3f97059af3282a, []int{1}
}

func (m *TaskRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaskRequest.Unmarshal(m, b)
}
func (m *TaskRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaskRequest.Marshal(b, m, deterministic)
}
func (m *TaskRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskRequest.Merge(m, src)
}
func (m *TaskRequest) XXX_Size() int {
	return xxx_messageInfo_TaskRequest.Size(m)
}
func (m *TaskRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TaskRequest proto.InternalMessageInfo

func (m *TaskRequest) GetTask() *Task {
	if m != nil {
		return m.Task
	}
	return nil
}

type TaskResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Task                 *Task    `protobuf:"bytes,2,opt,name=task,proto3" json:"task,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TaskResponse) Reset()         { *m = TaskResponse{} }
func (m *TaskResponse) String() string { return proto.CompactTextString(m) }
func (*TaskResponse) ProtoMessage()    {}
func (*TaskResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d3f97059af3282a, []int{2}
}

func (m *TaskResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaskResponse.Unmarshal(m, b)
}
func (m *TaskResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaskResponse.Marshal(b, m, deterministic)
}
func (m *TaskResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskResponse.Merge(m, src)
}
func (m *TaskResponse) XXX_Size() int {
	return xxx_messageInfo_TaskResponse.Size(m)
}
func (m *TaskResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TaskResponse proto.InternalMessageInfo

func (m *TaskResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *TaskResponse) GetTask() *Task {
	if m != nil {
		return m.Task
	}
	return nil
}

type GetTasksRequest struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTasksRequest) Reset()         { *m = GetTasksRequest{} }
func (m *GetTasksRequest) String() string { return proto.CompactTextString(m) }
func (*GetTasksRequest) ProtoMessage()    {}
func (*GetTasksRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d3f97059af3282a, []int{3}
}

func (m *GetTasksRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTasksRequest.Unmarshal(m, b)
}
func (m *GetTasksRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTasksRequest.Marshal(b, m, deterministic)
}
func (m *GetTasksRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTasksRequest.Merge(m, src)
}
func (m *GetTasksRequest) XXX_Size() int {
	return xxx_messageInfo_GetTasksRequest.Size(m)
}
func (m *GetTasksRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTasksRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetTasksRequest proto.InternalMessageInfo

func (m *GetTasksRequest) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type TasksResponse struct {
	Tasks                []*Task  `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TasksResponse) Reset()         { *m = TasksResponse{} }
func (m *TasksResponse) String() string { return proto.CompactTextString(m) }
func (*TasksResponse) ProtoMessage()    {}
func (*TasksResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d3f97059af3282a, []int{4}
}

func (m *TasksResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TasksResponse.Unmarshal(m, b)
}
func (m *TasksResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TasksResponse.Marshal(b, m, deterministic)
}
func (m *TasksResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TasksResponse.Merge(m, src)
}
func (m *TasksResponse) XXX_Size() int {
	return xxx_messageInfo_TasksResponse.Size(m)
}
func (m *TasksResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TasksResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TasksResponse proto.InternalMessageInfo

func (m *TasksResponse) GetTasks() []*Task {
	if m != nil {
		return m.Tasks
	}
	return nil
}

func init() {
	proto.RegisterEnum("remiderService.PRIORITY", PRIORITY_name, PRIORITY_value)
	proto.RegisterType((*Task)(nil), "remiderService.Task")
	proto.RegisterType((*TaskRequest)(nil), "remiderService.TaskRequest")
	proto.RegisterType((*TaskResponse)(nil), "remiderService.TaskResponse")
	proto.RegisterType((*GetTasksRequest)(nil), "remiderService.GetTasksRequest")
	proto.RegisterType((*TasksResponse)(nil), "remiderService.TasksResponse")
}

func init() {
	proto.RegisterFile("protoService/remiderService.proto", fileDescriptor_2d3f97059af3282a)
}

var fileDescriptor_2d3f97059af3282a = []byte{
	// 370 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x52, 0xd1, 0x8a, 0xda, 0x40,
	0x14, 0xed, 0x24, 0x51, 0x93, 0xab, 0x4d, 0x65, 0xe8, 0xc3, 0xa0, 0x95, 0xa6, 0x79, 0x28, 0xc1,
	0x82, 0x05, 0x5b, 0xe8, 0x43, 0xdf, 0x5a, 0x41, 0x53, 0xda, 0x5a, 0xa6, 0x42, 0xe9, 0xbe, 0xc8,
	0xec, 0xe6, 0x22, 0x83, 0x1b, 0xe3, 0x66, 0x66, 0x17, 0xf6, 0x83, 0xf6, 0x17, 0xf6, 0xfb, 0x96,
	0x8c, 0x89, 0x68, 0x50, 0xf6, 0x6d, 0xee, 0xb9, 0xe7, 0x9e, 0x7b, 0xce, 0x4d, 0xe0, 0xdd, 0x36,
	0xcf, 0x74, 0xf6, 0x17, 0xf3, 0x3b, 0x79, 0x85, 0x1f, 0x73, 0x4c, 0x65, 0x82, 0x79, 0x59, 0x8e,
	0x4c, 0x8f, 0xfa, 0xc7, 0x68, 0xf8, 0x48, 0xc0, 0x59, 0x08, 0xb5, 0xa6, 0x3e, 0x58, 0x32, 0x61,
	0x24, 0x20, 0x51, 0x83, 0x5b, 0x32, 0xa1, 0x0c, 0x5a, 0x29, 0x2a, 0x25, 0x56, 0xc8, 0xac, 0x80,
	0x44, 0x1e, 0xaf, 0x4a, 0x3a, 0x00, 0xb8, 0x96, 0xa9, 0xd4, 0xcb, 0x44, 0x68, 0x64, 0xb6, 0x69,
	0x7a, 0x06, 0x99, 0x08, 0x8d, 0x94, 0x82, 0xa3, 0xc5, 0x4a, 0x31, 0x27, 0xb0, 0x23, 0x8f, 0x9b,
	0x37, 0xed, 0x83, 0xa7, 0x51, 0xa4, 0xcb, 0x8d, 0x48, 0x91, 0x35, 0xcc, 0x84, 0x5b, 0x00, 0xbf,
	0x45, 0x8a, 0xf4, 0x33, 0xb8, 0xdb, 0x5c, 0x66, 0xb9, 0xd4, 0xf7, 0xac, 0x19, 0x90, 0xc8, 0x1f,
	0xb3, 0x51, 0xcd, 0xfb, 0x1f, 0x1e, 0xcf, 0x79, 0xbc, 0xf8, 0xcf, 0xf7, 0xcc, 0xf0, 0x0b, 0xb4,
	0x0b, 0xdf, 0x1c, 0x6f, 0x6e, 0x51, 0x69, 0x1a, 0x15, 0x5b, 0xd5, 0xda, 0x04, 0x68, 0x8f, 0x5f,
	0xd7, 0x05, 0x0c, 0xd5, 0x30, 0x42, 0x0e, 0x9d, 0xdd, 0xa0, 0xda, 0x66, 0x1b, 0x85, 0x87, 0x41,
	0xc9, 0x71, 0xd0, 0x4a, 0xd3, 0x7a, 0x56, 0xf3, 0x03, 0xbc, 0x9a, 0xa2, 0x2e, 0x00, 0x55, 0x19,
	0x3a, 0x2b, 0x1b, 0x7e, 0x85, 0x97, 0x25, 0xb3, 0x74, 0x30, 0x84, 0x46, 0xa1, 0xa2, 0x18, 0x09,
	0xec, 0xb3, 0x8b, 0x76, 0x94, 0xe1, 0x7b, 0x70, 0xab, 0x63, 0xd0, 0x16, 0xd8, 0x3f, 0xe7, 0xff,
	0xba, 0x2f, 0x8a, 0xc7, 0xaf, 0x78, 0xd2, 0x25, 0xd4, 0x05, 0x67, 0x16, 0x4f, 0x67, 0x5d, 0x6b,
	0xfc, 0x40, 0xc0, 0xe7, 0x47, 0x32, 0x74, 0x0a, 0xf0, 0x3d, 0x47, 0xa1, 0xd1, 0x7c, 0xef, 0xfe,
	0xc9, 0x2d, 0x3b, 0xf3, 0xbd, 0x37, 0xa7, 0x9b, 0xa5, 0xdf, 0x1f, 0xe0, 0x56, 0x69, 0xe9, 0xdb,
	0x3a, 0xb3, 0x76, 0x87, 0xde, 0xe0, 0x94, 0xd4, 0x3e, 0xfb, 0x37, 0xff, 0xa2, 0x73, 0xf8, 0xd3,
	0x5e, 0x36, 0x4d, 0xf5, 0xe9, 0x29, 0x00, 0x00, 0xff, 0xff, 0x8f, 0xc7, 0x50, 0xdc, 0xcb, 0x02,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// RemiderServiceClient is the client API for RemiderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RemiderServiceClient interface {
	CreateTask(ctx context.Context, in *TaskRequest, opts ...grpc.CallOption) (*TaskResponse, error)
	GetTasks(ctx context.Context, in *GetTasksRequest, opts ...grpc.CallOption) (*TasksResponse, error)
}

type remiderServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRemiderServiceClient(cc grpc.ClientConnInterface) RemiderServiceClient {
	return &remiderServiceClient{cc}
}

func (c *remiderServiceClient) CreateTask(ctx context.Context, in *TaskRequest, opts ...grpc.CallOption) (*TaskResponse, error) {
	out := new(TaskResponse)
	err := c.cc.Invoke(ctx, "/remiderService.RemiderService/CreateTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *remiderServiceClient) GetTasks(ctx context.Context, in *GetTasksRequest, opts ...grpc.CallOption) (*TasksResponse, error) {
	out := new(TasksResponse)
	err := c.cc.Invoke(ctx, "/remiderService.RemiderService/GetTasks", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RemiderServiceServer is the server API for RemiderService service.
type RemiderServiceServer interface {
	CreateTask(context.Context, *TaskRequest) (*TaskResponse, error)
	GetTasks(context.Context, *GetTasksRequest) (*TasksResponse, error)
}

// UnimplementedRemiderServiceServer can be embedded to have forward compatible implementations.
type UnimplementedRemiderServiceServer struct {
}

func (*UnimplementedRemiderServiceServer) CreateTask(ctx context.Context, req *TaskRequest) (*TaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTask not implemented")
}
func (*UnimplementedRemiderServiceServer) GetTasks(ctx context.Context, req *GetTasksRequest) (*TasksResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTasks not implemented")
}

func RegisterRemiderServiceServer(s *grpc.Server, srv RemiderServiceServer) {
	s.RegisterService(&_RemiderService_serviceDesc, srv)
}

func _RemiderService_CreateTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RemiderServiceServer).CreateTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/remiderService.RemiderService/CreateTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RemiderServiceServer).CreateTask(ctx, req.(*TaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RemiderService_GetTasks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTasksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RemiderServiceServer).GetTasks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/remiderService.RemiderService/GetTasks",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RemiderServiceServer).GetTasks(ctx, req.(*GetTasksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _RemiderService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "remiderService.RemiderService",
	HandlerType: (*RemiderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateTask",
			Handler:    _RemiderService_CreateTask_Handler,
		},
		{
			MethodName: "GetTasks",
			Handler:    _RemiderService_GetTasks_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protoService/remiderService.proto",
}
